// Template generated by reactGen

package main

import (
	"myitcv.io/react"

	"github.com/ladislavlisy/payroll-maestro-080318/client/app"
	"github.com/ladislavlisy/payroll-maestro-080318/client/isoclient"
	"github.com/ladislavlisy/payroll-maestro-080318/client/isoclient/common"

	"honnef.co/go/js/dom"
)

//go:generate reactGen

var document = dom.GetWindow().Document()

func main() {
	domTarget := document.GetElementByID("app")

	env := common.Env{}

	defer isoclient.RegisterRoutes(&env)

	react.Render(app.App(app.AppProps{BrandName: "React GopherJS"}), domTarget)
}
