language: go
before_install:
  - echo -e "machine github.com\n  login ladislavlisy\n  password $CI_USER_PASSWORD" > ~/.netrc
install: 
  - npm install
go:
  - "1.10.3"
before_script:
  - go get -u github.com/gopherjs/gopherjs
  - go get -u myitcv.io/react
  - export PATH="$(dirname $(go list -f '{{.Target}}' myitcv.io/react/cmd/reactGen)):$PATH"
script:
  - go get -u github.com/gin-gonic/gin
  - go get -u go.isomorphicgo.org/go/isokit
  - go get -u honnef.co/go/js/dom
  - pwd
  - ls -la
  - cd client && gopherjs build -o ../server/templates/js/client-app.js
  - cd server && go build -o payroll-maestro-server