# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.10.3
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/ladislavlisy/payroll-maestro-080318
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -u github.com/gopherjs/gopherjs
      - run: go get -u myitcv.io/react
      - run: echo 'export PATH="$(dirname $(go list -f '{{.Target}}' myitcv.io/react/cmd/reactGen)):$PATH"' >> $BASH_ENV
      - run: go get -u github.com/gin-gonic/gin
      - run: go get -u go.isomorphicgo.org/go/isokit
      - run: go get -u honnef.co/go/js/dom
      - run: pwd
      - run: |
          cd $CIRCLE_WORKING_DIRECTORY/client
          gopherjs build -o ../server/templates/js/client-app.js
      - run: |
          cd $CIRCLE_WORKING_DIRECTORY/server
          CGO_ENABLED=0 go build -o ../payroll-maestro-server
          chmod +x ../payroll-maestro-server
          ldd ../payroll-maestro-server

      - setup_remote_docker:          
          docker_layer_caching: true # (3)

      - run: |
         docker login -u $DOCKER_USER -p $DOCKER_PASS

      # build the application image
      - run: |
         pwd
         docker build -t ladislavlisy/payroll-maestro-080318:$CIRCLE_BRANCH /go/src/github.com/ladislavlisy/payroll-maestro-080318

      # deploy the image  
      - run: docker push ladislavlisy/payroll-maestro-080318:$CIRCLE_BRANCH