// Template generated by reactGen

package app

import (
	"myitcv.io/react"
)

//go:generate reactGen

type AppDef struct {
	react.ComponentDef
}

type AppProps struct {
	BrandName string
}

type AppState struct {
	userLoggedIn bool
}

func App(p AppProps) *AppElem {
	return buildAppElem(p)
}

func (a AppDef) ComponentWillMount() {
	s := a.State()
	s.userLoggedIn = false
	a.SetState(s)
}

func (a AppDef) Render() react.Element {
	if a.State().userLoggedIn {
		return UserSignedCentral(UserSignedCentralProps{BrandName: a.Props().BrandName, Title: "Sign Off", SignOffApp: a})
	} else {
		return UserSignInCentral(UserSignInCentralProps{BrandName: a.Props().BrandName, Title: "Sign In", SignInApp: a})
	}
}
