// Template generated by reactGen

package app

import (
	"github.com/ladislavlisy/payroll-maestro-080318/client/components"

	"myitcv.io/react"
)

//go:generate reactGen

type AppDef struct {
	react.ComponentDef
}

type AppProps struct {
	BrandName string
}

func App(p AppProps) *AppElem {
	return buildAppElem(p)
}

func (a AppDef) Render() react.Element {
	return react.Div(nil,
		components.Navigation(components.NavigationProps{BrandName: a.Props().BrandName}),
		react.Div(&react.DivProps{ClassName: "container", ID: "container"},
			react.H1(nil,
				react.S("Hello World "+a.Props().BrandName),
			),
			react.P(nil,
				react.S("This is my first GopherJS React App."),
			),
			components.LinkButton(components.LinkButtonProps{Title: "Sing in", Href: "/index"}),
		),
	)
}
