// Code generated by reactGen. DO NOT EDIT.

package app

import "myitcv.io/react"

type UserSignedCentralElem struct {
	react.Element
}

func buildUserSignedCentral(cd react.ComponentDef) react.Component {
	return UserSignedCentralDef{ComponentDef: cd}
}

func buildUserSignedCentralElem(props UserSignedCentralProps, children ...react.Element) *UserSignedCentralElem {
	return &UserSignedCentralElem{
		Element: react.CreateElement(buildUserSignedCentral, props, children...),
	}
}

func (u UserSignedCentralDef) RendersElement() react.Element {
	return u.Render()
}

// IsProps is an auto-generated definition so that UserSignedCentralProps implements
// the myitcv.io/react.Props interface.
func (u UserSignedCentralProps) IsProps() {}

// Props is an auto-generated proxy to the current props of UserSignedCentral
func (u UserSignedCentralDef) Props() UserSignedCentralProps {
	uprops := u.ComponentDef.Props()
	return uprops.(UserSignedCentralProps)
}

func (u UserSignedCentralProps) EqualsIntf(val react.Props) bool {
	return u == val.(UserSignedCentralProps)
}

var _ react.Props = UserSignedCentralProps{}
