// Code generated by reactGen. DO NOT EDIT.

package app

import "myitcv.io/react"

type ClickButtonElem struct {
	react.Element
}

func buildClickButton(cd react.ComponentDef) react.Component {
	return ClickButtonDef{ComponentDef: cd}
}

func buildClickButtonElem(props ClickButtonProps, children ...react.Element) *ClickButtonElem {
	return &ClickButtonElem{
		Element: react.CreateElement(buildClickButton, props, children...),
	}
}

func (c ClickButtonDef) RendersElement() react.Element {
	return c.Render()
}

// IsProps is an auto-generated definition so that ClickButtonProps implements
// the myitcv.io/react.Props interface.
func (c ClickButtonProps) IsProps() {}

// Props is an auto-generated proxy to the current props of ClickButton
func (c ClickButtonDef) Props() ClickButtonProps {
	uprops := c.ComponentDef.Props()
	return uprops.(ClickButtonProps)
}

func (c ClickButtonProps) EqualsIntf(val react.Props) bool {
	return c == val.(ClickButtonProps)
}

var _ react.Props = ClickButtonProps{}
