// Code generated by reactGen. DO NOT EDIT.

package app

import "myitcv.io/react"

type UserSignInCentralElem struct {
	react.Element
}

func buildUserSignInCentral(cd react.ComponentDef) react.Component {
	return UserSignInCentralDef{ComponentDef: cd}
}

func buildUserSignInCentralElem(props UserSignInCentralProps, children ...react.Element) *UserSignInCentralElem {
	return &UserSignInCentralElem{
		Element: react.CreateElement(buildUserSignInCentral, props, children...),
	}
}

func (u UserSignInCentralDef) RendersElement() react.Element {
	return u.Render()
}

// IsProps is an auto-generated definition so that UserSignInCentralProps implements
// the myitcv.io/react.Props interface.
func (u UserSignInCentralProps) IsProps() {}

// Props is an auto-generated proxy to the current props of UserSignInCentral
func (u UserSignInCentralDef) Props() UserSignInCentralProps {
	uprops := u.ComponentDef.Props()
	return uprops.(UserSignInCentralProps)
}

func (u UserSignInCentralProps) EqualsIntf(val react.Props) bool {
	return u == val.(UserSignInCentralProps)
}

var _ react.Props = UserSignInCentralProps{}
