// Code generated by reactGen. DO NOT EDIT.

package app

import "myitcv.io/react"

type AppElem struct {
	react.Element
}

func buildApp(cd react.ComponentDef) react.Component {
	return AppDef{ComponentDef: cd}
}

func buildAppElem(props AppProps, children ...react.Element) *AppElem {
	return &AppElem{
		Element: react.CreateElement(buildApp, props, children...),
	}
}

func (a AppDef) RendersElement() react.Element {
	return a.Render()
}

// IsProps is an auto-generated definition so that AppProps implements
// the myitcv.io/react.Props interface.
func (a AppProps) IsProps() {}

// Props is an auto-generated proxy to the current props of App
func (a AppDef) Props() AppProps {
	uprops := a.ComponentDef.Props()
	return uprops.(AppProps)
}

func (a AppProps) EqualsIntf(val react.Props) bool {
	return a == val.(AppProps)
}

var _ react.Props = AppProps{}
