// Code generated by reactGen. DO NOT EDIT.

package components

import "myitcv.io/react"

type LinkButtonElem struct {
	react.Element
}

func buildLinkButton(cd react.ComponentDef) react.Component {
	return LinkButtonDef{ComponentDef: cd}
}

func buildLinkButtonElem(props LinkButtonProps, children ...react.Element) *LinkButtonElem {
	return &LinkButtonElem{
		Element: react.CreateElement(buildLinkButton, props, children...),
	}
}

func (l LinkButtonDef) RendersElement() react.Element {
	return l.Render()
}

// IsProps is an auto-generated definition so that LinkButtonProps implements
// the myitcv.io/react.Props interface.
func (l LinkButtonProps) IsProps() {}

// Props is an auto-generated proxy to the current props of LinkButton
func (l LinkButtonDef) Props() LinkButtonProps {
	uprops := l.ComponentDef.Props()
	return uprops.(LinkButtonProps)
}

func (l LinkButtonProps) EqualsIntf(val react.Props) bool {
	return l == val.(LinkButtonProps)
}

var _ react.Props = LinkButtonProps{}
